--- 
layout: post
title: Italian Cybespace Law Conference
published: true
meta: {}

tags: 
- Conferenze
- Security and Intelligence
type: post
status: publish
---
 <div style="clear:both;"></div>Eccomi tornato dopo una pausa di blogging dovuta essenzialmente al troppo stress :)<br /> Ed eccomi giusto giusto di ritorno dall'Italian Cyberspace Law Conference (<a href="http://www.iclc.org/">www.iclc.org</a>). Un evento unico in italia che vede la partecipazione dei gruppi di esperti legati alla Computer Forensic: avvocati, magistrati, forze dell'ordine e, ovviamente, consulenti.<br /><br />  E' stata l'occasione per sentire paralare dal vivo il Dott. <b>Gerardo Costabile</b>, della GdF, ma anche notare gli interventi dei difensori in tutela delle pratiche. In questo senso sono stati illuminanti gli interventi dell'avvocato <b>Luca Lupària</b>. Devo dire che anche se non mi sono trovato daccordo con alcuni suoi punti mi sono però dovuto piegare alle ottime argomentazioni ed alle acute osservazioni...<br /><br /><br /> Altro discorso i normali e probabilmente annunciati screzi con l'ottimo Avvocato <b>Andrea Monti</b>, noto difensore in dibattiti su crimini informatici con cui ho avuto modo di scambiare qualche parola, trovandolo estremamente compentente e forse un pelo troppo sofista per i miei gusti, anche se il mio ed il suo lavoro si posizionano per ora dagli opposti lati della barricata e posso benissimo capire che il sofismo fa parte integrante della sua professione...<br /><br /> Sinceramente mi sarei aspettato di più dal Prof. <b>Cesare Maioli</b>: il suo intervento sulle Best Practices di Computer Forensic mi è semprato a dir tanto introduttivo, per nulla originale e di contenuti assai scarsi. Qualunque manuale for dummies di procedura forense potrebbe facilmente trattare le stesse cose in maggiore dettaglio. Probabilmente, però, la colpa è del tempo eccessivamente breve per l'esposizione e non di una conoscenza frammentaria del campo.<br /><br />  Che dire di altro? Ho avuto modo di apprezzare il <a href="http://www.ziccardi.org/">Dott. Ziccardi</a> ancora una volta, di spirito faceto, ottimo chairman e soprattutto estremamente competente sia nei riassunti dei contenuti e sia negli interventi. Credo che in italia, per quanto riguardi Privacy e Diritto, sia una delle voci sicuramente più autorevoli, se non la più competente. Credo mi piacerebbe lavorare a qualcosa con lui. L'intervento poi dell'avvocato Melica è stato particolarmente toccante.<br /><br /> Un ottima e proficua full immersion di due giorni in attesa dei prossimi eventi.<div style="clear:both; padding-bottom: 0.25em;"></div> 
