--- 
layout: post
title: Disclosure
published: true
meta: 
  _wp_page_template: default
  autometa: advertisements compensation topics owner opinions products forms product
tags: 
- Me &amp; The Web
type: post
status: publish
---
This policy is valid from 30 October 2006  
  
 This blog is a personal blog written and edited by me. This blog accepts forms of cash advertising, sponsorship, paid insertions or other forms of compensation.  
  
 The compensation received will never influence the content, topics or posts made in this blog. All advertising is in the form of advertisements generated by a third party ad network. Those advertisements will be identified as paid advertisements.  
  
 The owner(s) of this blog is compensated to provide opinion on products, services, websites and various other topics. Even though the owner(s) of this blog receives compensation for our posts or advertisements, we always give our honest opinions, findings, beliefs, or experiences on those topics or products. The views and opinions expressed on this blog are purely the bloggers' own. Any product claim, statistic, quote or other representation about a product or service should be verified with the manufacturer, provider or party in question.  
  
 The owner(s) of this blog would like to disclose the following existing relationships. These are companies, organizations or individuals that may have a significant impact on the content of this blog. We are employed by or consult with: LkProject, Khamsa, LastKnight Dot Com, 77Agency. We serve on the following corporate or non profit boards: AipNet, Opsi.  
  
To get your own policy, go to [http://www.disclosurepolicy.org]   
